### ISSUE TITLE
`#` gets replaced with `/` in url

### ISSUE THREAD

**Issue by marcbachmann** [choojs/nanorouter#7]
I'm using choo and just found this really weird behavior, which looks like a bug.
When you open a url that contains a `#`, it gets replaced with `/`, which causes a route not to match. e.g. `/test#foo` is transformed to `/test/foo`

I would have expected that `/test#foo` matches the route `/test`.
To fix the issue we could change the `suffix` regex on [line 10](https://github.com/choojs/nanorouter/blob/master/index.js#L10) to include the `#`.
And btw, there's no need to escape `?` in character sets.

```diff
@@ -7,7 +7,7 @@ var isLocalFile = (/file:\/\//.test(typeof window === 'object' &&
 var electron = '^(file:\/\/|\/)(.*\.html?\/?)?'
 var protocol = '^(http(s)?(:\/\/))?(www\.)?'
 var domain = '[a-zA-Z0-9-_\.]+(:[0-9]{1,5})?(\/{1})?'
-var qs = '[\?].*$'
+var qs = '[?#].*$'
 /* eslint-enable no-useless-escape */
 
 var stripElectron = new RegExp(electron)
```

### How to reproduce it
```js
// launch with `bankai start ./test.js` and open https://localhost:8080/test#foo
const choo = require('choo')()
const html = require('bel')

choo.route('/test', function (state) {
  return html`
    <body>
      This route does not match: /test#foo<br>
      state.route: ${state.route}<br>
      state.href: ${state.href}
    </body>
  `
})

choo.route('/test/foo', function (state) {
  return html`
    <body>
      This route matches: /test#foo<br>
      state.route: ${state.route}<br>
      state.href: ${state.href}
    </body>
  `
})

choo.mount('body')
```

![image](https://user-images.githubusercontent.com/431376/34330002-720171c4-e915-11e7-9451-b55163edc50f.png)

And sorry for writing on christmas 😆.
I just got home and began coding 🤦‍♂️ .

**Comment by marcbachmann** [comment]
I guess this is currently in use for pushstate support.
In my case I'm using `/login#token=tokenfromserver` to log somebody into the app in an oauth-like authentication flow. The route sign is used to prevent the client from sending the secret to the server.

So this could be a feature request.. or a change request. Maybe some config is needed to differentiate between the behaviors.

**Comment by marcbachmann** [comment]
Ok, another location where it gets converted is in https://github.com/choojs/choo/blame/master/index.js#L41

**Comment by marcbachmann** [comment]
Oh, that's how you're using routes https://github.com/choojs/choo/blob/master/example/index.js#L14

```
app.route('/', require('./view'))
app.route('#active', require('./view'))
app.route('#completed', require('./view'))
app.route('*', require('./view'))
```

I could live with that workaround/behavior, but it was a bit unexpected to see this.
That should be documented somewhere.

**Comment by marcbachmann** [comment]
Closing for now as this would be a breaking change in choo.

**Comment by yoshuawuyts** [comment]
@marcbachmann heya, yeah sorry this isn't working the way you'd hoped. The hash routing has always been a bit of a tricky one.

We merged [our routing docs](https://github.com/choojs/website/blob/master/content/reference/routing.md#hash-routing) today. Could you perhaps take a look to see if the information you were missing now exists? That'd be a great help so that nobody runs into this in the future!

Separate from that, I do agree that having routes like `/foo/bar#baz` should work. Perhaps we could do some work on that too?

Thanks heaps for the very detailed issue!

**Comment by marcbachmann** [comment]
No problem, it just was very unexpected. I spent some time on it to figure out what happened.
Thanks, the docs PR is how I found that functionality.

> Separate from that, I do agree that having routes like /foo/bar#baz should work. Perhaps we could do some work on that too?

Yep, maybe with another match when the hash is present.
